"""add message chat attachment table and add createat in other tables

Revision ID: 60d3359cd349
Revises: 9b3d2784b74e
Create Date: 2024-11-18 23:21:17.806929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60d3359cd349'
down_revision = '9b3d2784b74e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
