"""add token blacklists table

Revision ID: 9c257a39bb27
Revises: 3b4de6d53aac
Create Date: 2024-11-19 02:12:50.213408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c257a39bb27'
down_revision = '3b4de6d53aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklists',
    sa.Column('TOKEN_ID', sa.Integer(), nullable=False),
    sa.Column('JTI', sa.String(length=36), nullable=False),
    sa.Column('CREATED_AT', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('TOKEN_ID'),
    sa.UniqueConstraint('JTI')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_blacklists')
    # ### end Alembic commands ###
